#pragma once
#ifndef NEWALARMDATA_H
#define NEWALARMDATA_H

namespace cl {
	enum Alarm_Type
	{
		ALARM_KNIFE = 1,
		ALARM_GRENADE,
		ALARM_HEADSHOT,
		ALARM_KILL,
		ALARM_2KILL,
		ALARM_3KILL,
		ALARM_4KILL,
		ALARM_FIRSTBLOOD,
		ALARM_PAYBACK,
		ALARM_EXCELLENT,
		ALARM_INCREDIBLE,
		ALARM_CRAZY,
		ALARM_CANTBELIEVE,
		ALARM_OUTOFWORLD,
		ALARM_LIBERATOR,
		ALARM_ALLROUND,
		ALARM_INFECTOR,
		ALARM_SUPPORTER,
		ALARM_KINGMAKER,
		ALARM_ASSIST,
		ALARM_THELAST,
		ALARM_LASTSOLDIER,
		ALARM_SAVIOR,
		ALARM_INVISHAND,
		ALARM_KINGMURDER,
		ALARM_BACKMARKER,
		ALARM_WELCOME,
		ALARM_COMEBACK,
		ALARM_C4MANKILL,
		ALARM_C4PLANT,
		ALARM_C4PLANTBLOCK,
		ALARM_C4DEFUSTBLOCK,
		ALARM_ZOMBIEBOMB,
		ALARM_ZOMBIETANKER,
		ALARM_INTOXICATION,
		ALARM_REVIVALWILL,
		ALARM_MAXLEVEL,
		ALARM_PROFESSIONAL,
		ALARM_UNTOUCHABLE,
		ALARM_DESTRUCTION,
		ALARM_TERMINATION,
		ALARM_RESCUE,
		ALARM_COMBO,
		ALARM_ALIVE,
		ALARM_NOPARASHUTE,
		ALARM_CHICKENCHASER,

		ALARM_OVERRUN,
		ALARM_ATTACKER,
		ALARM_BESTMOMENT,
		ALARM_HOLDOUT,
		ALARM_BATPULL,
		ALARM_DROPWEAPON,
		ALARM_HIDE,
		ALARM_HEALER,
		ALARM_LAST
	};

}
#endif