#pragma once

#define ADD_NAMED_ARGUMENT(Z, I, ARGSTYPE_TUPLE) typename TypeIdentity<BOOST_PP_TUPLE_ELEM(I, ARGSTYPE_TUPLE)>::type BOOST_PP_CAT(x, BOOST_PP_DEC(I))
#define NAMED_ARGUMENT(...) BOOST_PP_IF(BOOST_PP_EQUAL(BOOST_PP_VARIADIC_SIZE(__VA_ARGS__), 1), (), (BOOST_PP_ENUM_SHIFTED(BOOST_PP_VARIADIC_SIZE(__VA_ARGS__), ADD_NAMED_ARGUMENT, (__VA_ARGS__))))
#define NAMED_ARGUMENT_THIS(THISCLASS, ...) BOOST_PP_IF(BOOST_PP_EQUAL(BOOST_PP_VARIADIC_SIZE(__VA_ARGS__), 1), (THISCLASS *that), (THISCLASS *that, BOOST_PP_ENUM_SHIFTED(BOOST_PP_VARIADIC_SIZE(__VA_ARGS__), ADD_NAMED_ARGUMENT, (__VA_ARGS__))))

#define NAMED_ARG_FN_DECL(...) auto BOOST_PP_VARIADIC_ELEM(0, __VA_ARGS__) NAMED_ARGUMENT(__VA_ARGS__)