
#ifndef WEAPONS_CONST_H
#define WEAPONS_CONST_H
#ifdef _WIN32
#pragma once
#endif

enum WeaponIdType
{
	WEAPON_NONE,
	WEAPON_P228,
	WEAPON_GLOCK,
	WEAPON_SCOUT,
	WEAPON_HEGRENADE,
	WEAPON_XM1014,
	WEAPON_C4,
	WEAPON_MAC10,
	WEAPON_AUG,
	WEAPON_SMOKEGRENADE,
	WEAPON_ELITE,
	WEAPON_FIVESEVEN,
	WEAPON_UMP45,
	WEAPON_SG550,
	WEAPON_GALIL,
	WEAPON_FAMAS,
	WEAPON_USP,
	WEAPON_GLOCK18,
	WEAPON_AWP,
	WEAPON_MP5N,
	WEAPON_M249,
	WEAPON_M3,
	WEAPON_M4A1,
	WEAPON_TMP,
	WEAPON_G3SG1,
	WEAPON_FLASHBANG,
	WEAPON_DEAGLE,
	WEAPON_SG552,
	WEAPON_AK47,
	WEAPON_KNIFE,
	WEAPON_P90,
	WEAPON_SHIELDGUN = 99
};

enum AmmoType
{
	AMMO_BUCKSHOT,
	AMMO_9MM,
	AMMO_556NATO,
	AMMO_556NATOBOX,
	AMMO_762NATO,
	AMMO_45ACP,
	AMMO_50AE,
	AMMO_338MAGNUM,
	AMMO_57MM,
	AMMO_357SIG,
	AMMO_MAX_TYPES,
};

enum WeaponState
{
	WPNSTATE_USP_SILENCED = (1 << 0),
	WPNSTATE_GLOCK18_BURST_MODE = (1 << 1),
	WPNSTATE_M4A1_SILENCED = (1 << 2),
	WPNSTATE_ELITE_LEFT = (1 << 3),
	WPNSTATE_FAMAS_BURST_MODE = (1 << 4),
	WPNSTATE_SHIELD_DRAWN = (1 << 5),
};

// custom enum
// the default amount of ammo that comes with each gun when it spawns
enum ClipGiveDefault
{
	P228_DEFAULT_GIVE = 13,
	GLOCK18_DEFAULT_GIVE = 20,
	SCOUT_DEFAULT_GIVE = 10,
	HEGRENADE_DEFAULT_GIVE = 1,
	XM1014_DEFAULT_GIVE = 7,
	C4_DEFAULT_GIVE = 1,
	MAC10_DEFAULT_GIVE = 30,
	AUG_DEFAULT_GIVE = 30,
	SMOKEGRENADE_DEFAULT_GIVE = 1,
	ELITE_DEFAULT_GIVE = 30,
	FIVESEVEN_DEFAULT_GIVE = 20,
	UMP45_DEFAULT_GIVE = 25,
	SG550_DEFAULT_GIVE = 30,
	GALIL_DEFAULT_GIVE = 35,
	FAMAS_DEFAULT_GIVE = 25,
	USP_DEFAULT_GIVE = 12,
	AWP_DEFAULT_GIVE = 10,
	MP5NAVY_DEFAULT_GIVE = 30,
	M249_DEFAULT_GIVE = 100,
	M3_DEFAULT_GIVE = 8,
	M4A1_DEFAULT_GIVE = 30,
	TMP_DEFAULT_GIVE = 30,
	G3SG1_DEFAULT_GIVE = 20,
	FLASHBANG_DEFAULT_GIVE = 1,
	DEAGLE_DEFAULT_GIVE = 7,
	SG552_DEFAULT_GIVE = 30,
	AK47_DEFAULT_GIVE = 30,
	/*KNIFE_DEFAULT_GIVE		= 1,*/
	P90_DEFAULT_GIVE = 50,
};

enum ClipSizeType
{
	P228_MAX_CLIP = 13,
	GLOCK18_MAX_CLIP = 20,
	SCOUT_MAX_CLIP = 10,
	XM1014_MAX_CLIP = 7,
	MAC10_MAX_CLIP = 30,
	AUG_MAX_CLIP = 30,
	ELITE_MAX_CLIP = 30,
	FIVESEVEN_MAX_CLIP = 20,
	UMP45_MAX_CLIP = 25,
	SG550_MAX_CLIP = 30,
	GALIL_MAX_CLIP = 35,
	FAMAS_MAX_CLIP = 25,
	USP_MAX_CLIP = 12,
	AWP_MAX_CLIP = 10,
	MP5N_MAX_CLIP = 30,
	M249_MAX_CLIP = 100,
	M3_MAX_CLIP = 8,
	M4A1_MAX_CLIP = 30,
	TMP_MAX_CLIP = 30,
	G3SG1_MAX_CLIP = 20,
	DEAGLE_MAX_CLIP = 7,
	SG552_MAX_CLIP = 30,
	AK47_MAX_CLIP = 30,
	P90_MAX_CLIP = 50,
};

enum MaxAmmoType
{
	MAX_AMMO_BUCKSHOT = 32,
	MAX_AMMO_9MM = 120,
	MAX_AMMO_556NATO = 90,
	MAX_AMMO_556NATOBOX = 200,
	MAX_AMMO_762NATO = 90,
	MAX_AMMO_45ACP = 100,
	MAX_AMMO_50AE = 35,
	MAX_AMMO_338MAGNUM = 30,
	MAX_AMMO_57MM = 100,
	MAX_AMMO_357SIG = 52,

	// custom
	MAX_AMMO_SMOKEGRENADE = 1,
	MAX_AMMO_HEGRENADE = 1,
	MAX_AMMO_FLASHBANG = 2,
	MAX_AMMO_C4 = 1,
};

enum WeightWeapon
{
	P228_WEIGHT = 5,
	GLOCK18_WEIGHT = 5,
	SCOUT_WEIGHT = 30,
	HEGRENADE_WEIGHT = 2,
	XM1014_WEIGHT = 20,
	C4_WEIGHT = 3,
	MAC10_WEIGHT = 25,
	AUG_WEIGHT = 25,
	SMOKEGRENADE_WEIGHT = 1,
	ELITE_WEIGHT = 5,
	FIVESEVEN_WEIGHT = 5,
	UMP45_WEIGHT = 25,
	SG550_WEIGHT = 20,
	GALIL_WEIGHT = 25,
	FAMAS_WEIGHT = 75,
	USP_WEIGHT = 5,
	AWP_WEIGHT = 30,
	MP5NAVY_WEIGHT = 25,
	M249_WEIGHT = 25,
	M3_WEIGHT = 20,
	M4A1_WEIGHT = 25,
	TMP_WEIGHT = 25,
	G3SG1_WEIGHT = 20,
	FLASHBANG_WEIGHT = 1,
	DEAGLE_WEIGHT = 7,
	SG552_WEIGHT = 25,
	AK47_WEIGHT = 25,
	P90_WEIGHT = 26,
	KNIFE_WEIGHT = 0,
};


enum shieldgun_e
{
	SHIELDGUN_IDLE,
	SHIELDGUN_SHOOT1,
	SHIELDGUN_SHOOT2,
	SHIELDGUN_SHOOT_EMPTY,
	SHIELDGUN_RELOAD,
	SHIELDGUN_DRAW,
	SHIELDGUN_DRAWN_IDLE,
	SHIELDGUN_UP,
	SHIELDGUN_DOWN,
};

// custom
enum shieldgren_e
{
	SHIELDREN_IDLE = 4,
	SHIELDREN_UP,
	SHIELDREN_DOWN
};

enum InventorySlotType
{
	PRIMARY_WEAPON_SLOT = 1,
	PISTOL_SLOT,
	KNIFE_SLOT,
	GRENADE_SLOT,
	C4_SLOT,
};

enum Bullet
{
	BULLET_NONE,
	BULLET_PLAYER_9MM,
	BULLET_PLAYER_MP5,
	BULLET_PLAYER_357,
	BULLET_PLAYER_BUCKSHOT,
	BULLET_PLAYER_CROWBAR,
	BULLET_MONSTER_9MM,
	BULLET_MONSTER_MP5,
	BULLET_MONSTER_12MM,
	BULLET_PLAYER_45ACP,
	BULLET_PLAYER_338MAG,
	BULLET_PLAYER_762MM,
	BULLET_PLAYER_556MM,
	BULLET_PLAYER_50AE,
	BULLET_PLAYER_57MM,
	BULLET_PLAYER_357SIG,
};

#endif
