/*
weapons_moe_buy.h - CSMoE Gameplay server : Weapon buy command handler
Copyright (C) 2019 Moemod Hymei

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
*/

#ifndef WEAPONS_MOE_BUY_H
#define WEAPONS_MOE_BUY_H

#include "player/player_const.h"

#ifdef _WIN32
#pragma once
#endif

#ifdef CLIENT_DLL
namespace cl {
#else
namespace sv {
#endif

enum MoEWeaponBuyType
{
    BUY_NONE = -1,
    BUY_PISTOL = 0,
    BUY_SHOTGUN,
    BUY_SMG,
    BUY_RIFLE,
    BUY_MG,
    BUY_EQUIP,
    BUY_KNIFE
};

struct MoEWeaponBuyInfo_s
{
	int iID;
	const char* pszClassName;
	const char* pszDisplayName;
	int iCost;
	InventorySlotType iSlot;
	TeamName iTeam;
    MoEWeaponBuyType iMenu;
};

constexpr MoEWeaponBuyInfo_s g_MoEWeaponBuyInfo[] = {
    { WEAPON_USP, "weapon_usp",      "USP45",    500, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
    { WEAPON_GLOCK18, "weapon_glock18",      "Glock-18",    400, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
    { WEAPON_P228, "weapon_p228",      "P228",    600, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
    { WEAPON_DEAGLE, "weapon_deagle",      "Deagle",    650, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
    { WEAPON_ELITE, "weapon_elite",      "Elite",    800, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
    { WEAPON_FIVESEVEN, "weapon_fiveseven",      "FiveSeven",    750, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
    { WEAPON_M3, "weapon_m3",      "M3",    1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
    { WEAPON_XM1014, "weapon_xm1014",      "XM1014",    3000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
    { WEAPON_MAC10, "weapon_mac10",      "MAC10",    1400, PRIMARY_WEAPON_SLOT, UNASSIGNED,  BUY_SMG },
    { WEAPON_TMP, "weapon_tmp",      "TMP",    1250, PRIMARY_WEAPON_SLOT, UNASSIGNED,  BUY_SMG },
    { WEAPON_MP5N, "weapon_mp5navy",      "MP5",    1500, PRIMARY_WEAPON_SLOT, UNASSIGNED,  BUY_SMG },
    { WEAPON_UMP45, "weapon_ump45",      "UMP-45",    1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
    { WEAPON_P90, "weapon_p90",      "P90",    2350, PRIMARY_WEAPON_SLOT, UNASSIGNED,  BUY_SMG },
    { WEAPON_GALIL, "weapon_galil",      "Galil",    2000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_FAMAS, "weapon_famas",      "Famas",    2250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_AK47, "weapon_ak47",      "CV-47",    2500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_SCOUT, "weapon_scout",      "Scout",    2750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_M4A1, "weapon_m4a1",      "M4A1",    3100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_AUG, "weapon_aug",      "AUG",    3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_SG552, "weapon_sg552",      "SG552",    3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_SG550, "weapon_sg550",      "SG550",    4200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_AWP, "weapon_awp",      "AWP",    4750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_G3SG1, "weapon_g3sg1",      "G3SG1",    5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_M249, "weapon_m249",      "M249",    5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },

    { WEAPON_KNIFE, "weapon_knife", "海豹短刀",            0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },

//#ifdef XASH_DEDICATED
	{ WEAPON_Z4B_INFINITYX, "z4b_infinityx", "英菲尼迪双枪",     1500, PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_VOIDPISTOL, "weapon_voidpistol",         "黑曜审判",                  1700, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_GUNKATA, "weapon_gunkata",	 "深渊",			  1500,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_DESPERADO, "weapon_desperado",         "永恒",                  1500, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_Y21S1JETGUNMD, "weapon_y21s1jetgunmd",  "冰雪魔咒",	2000, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_Z4B_FREQUENCY1, "z4b_frequency1",        "劫曦F1",                  1500, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_Z4B_DEAGLESHURA, "z4b_deagleb",      "修罗",    700, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_DEAGLED, "weapon_deagled",      "双持沙鹰",    700, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	//{ WEAPON_Z4B_M37SE, "z4b_m37se",         "恶棍",                  2700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_HUNTBOW, "weapon_huntbow",      "魂狩猎弓",               6200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_GUNGNIR, "weapon_gungnir",     "断狱雷魂",               6000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_SGDRILL, "weapon_sgdrill",         "怒海狂鲨",                 6250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_GATLINGEX, "weapon_gatlingex",        "日冕加特林",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_LASERSG, "weapon_lasersg",         "【异噬】暗雷兽",                  4000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_M3DRAGON, "weapon_m3dragon",         "【天龙】m3",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_M3DRAGONM, "weapon_m3dragonm",         "巨齿鲲鲨",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_BUFFSG552EX, "weapon_buffsg552ex",         "熔火岩狼",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_QBARREL, "weapon_qbarrel",         "破碎炙燚",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_BUFFM249, "weapon_buffm249",      "朱雀",    9000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_STUNRIFLE, "weapon_stunrifle",      "雷电风暴",    3600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_BUFFM4, "weapon_buffm4",      "邪皇",    5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_BUFFAK, "weapon_buffak",      "圣帝",    5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_REVIVEGUN, "weapon_revivegun",	 "逆界星轮",			  6000,  PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_Z4B_CANNONPLASMA, "z4b_cannonplasma",      "黎明离子炮",    3800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_Z4B_CANNONTIGER, "z4b_cannontiger",      "裂地虎炮",    3800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_Z4B_M134HEROI, "z4b_m134heroi",      "漩涡i7",    7700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_Z4B_XM2010PC, "z4b_xm2010pc",      "罪恶虚空",    7700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_Z4B_AWPNVIDIA, "z4b_awpnvidia",      "矿难AWP",    4650, PRIMARY_WEAPON_SLOT, UNASSIGNED,BUY_RIFLE },
	{ WEAPON_Z4B_M4A1RAZER, "z4b_m4a1razer",      "雷蛇M4A1",    4250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_Z4B_MP7A1DX, "z4b_dmp7a1x",      "双持审判效应N7",    2350, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_Z4B_M4A1X, "z4b_m4a1x",      "绝影M4A1",    4288, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_Z4B_AK47X, "z4b_ak47x",      "黑武士AK47",    4288, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_Z4B_M4A1MW, "z4b_m4a1mw",      "暗羽冥王M4A1",    3600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	
	{ WEAPON_Z4B_BARRETTD, "z4b_barrettd",        "毁灭巴菲特",                  5288, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_CHEYTACLRRS, "weapon_cheytaclrrs",         "CheytacLRRS-M200",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_Z4B_K1ASES, "z4b_k1ases",        "银蝎K1A",                  8000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_Z4B_M1887SE, "z4b_m1887se",        "降魔圣焰M1887",                  5500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AK47_LONG, "weapon_ak47l",      "AK47-旋风",    2500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_MP7A1D, "weapon_mp7a1d",      "双持MP7",    1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_M32VENOM, "weapon_m32venom", "腐化重炮", 6500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_M95TIGER, "weapon_m95tiger",         "【虎王】M95",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_Y20S2SCARD, "weapon_y20s2scard",         "绿野仙踪SCARD",           1500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_JANUS7XMAS, "weapon_janus7xmas",         "圣诞雷狱",                  9000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_SPSMG, "weapon_spsmg",	 "爆炎蒸汽",			  2500,  PRIMARY_WEAPON_SLOT,         UNASSIGNED, BUY_SMG },

	{ KNIFE_LANCE, "knife_lance",     "天罚龙枪",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_DUALSWORD, "knife_dualsword",    "弑神双剑",0, KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_DGAXE, "knife_dgaxe",     "神鬼开天",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_STORMGIANT, "knife_stormgiant",      "星陨巨锤",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_SKULLT9, "knife_skullt9",     "阵风T9",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_RUNEBLADE, "knife_runeblade",      "【魔魂】重剑",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Z4B_FREQUENCY9, "z4b_Frequency9",      "迷迭F9",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Z4B_LCSWORD, "z4b_lc_sword",      "军团指挥官圣剑",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Z4B_FACELESSVOID, "z4b_facelessvoid",      "虚空假面智杖",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Z4B_STRONGKNIFEX, "z4b_strongknifex",      "新月刃",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Z4B_NATAKNIFEDX, "z4b_nataknifedx",      "双持新月刃",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Z4B_OPPOVIVO, "z4b_oppovivo",      "绝地光剑",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Z4B_STORMGIANTX, "z4b_stormgiantx",      "骇影巨锤",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_SUMMONKNIFE, "knife_summonknife",     "星际仲裁",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_HOLYSWORD, "knife_holysword",     "【辉煌】圣剑",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_MAGICKNIFE, "knife_magicknife",     "幻镜！光棱剑",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_THANATOS9, "knife_thanatos9",      "陨裂",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	//{ WEAPON_SMOKEGRENADE, "weapon_molotov",         "燃烧瓶",                  600, GRENADE_SLOT, UNASSIGNED, BUY_EQUIP },
	{ KNIFE_NATAKNIFED, "knife_nataknifed",      "双持银刃",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Y22S1HOLYSWORDMB, "knife_y22s1holyswordmb",         "【奇幻乐园】双手剑",           0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_WHIPSWORD, "knife_whipsword",     "【极影】蛇心剑",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_Y22S2SFSWORD, "knife_y22s2sfsword",      "粒子激光剑Ex",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ WEAPON_PIANOGUN, "weapon_pianogun",        "【命运】寂静之音",                  7000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_CANNONEX, "weapon_cannonex",         "赤焰魔龙",           6500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_SPEARGUN, "weapon_speargun",         "海皇之怒",           5800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_SGMISSILE, "weapon_sgmissile",        "撼宇碎星",                  6400, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_SGMISSILEM, "weapon_sgmissilem",        "爆烈神机弩",                  6250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_SGMISSILEEX, "weapon_sgmissileex",        "撼宇碎星Zero",                  6250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_WINGGUN, "weapon_winggun",        "曙光辉翼",                  6100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_WONDERCANNON, "weapon_wondercannon",        "炽麟煌焱",                  6250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_CSGO_CZ75, "csgo_cz75",         "CZ75",                  500, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_CSGO_TEC9, "csgo_tec9",         "Tec-9",                  500, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_CSGO_R8, "csgo_r8",        "左轮R8",                  850, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_CSGO_NEGEV, "csgo_negev",         "内格夫Negev",                  1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_CSGO_MAG7, "csgo_mag7",         "警喷MAG-7",                  1800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_CSGO_SAWEDOFF, "csgo_sawedoff",         "匪喷Sawed-Off",                  1100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_CSGO_BIZON, "csgo_bizon",         "野牛PP-Bizon",                  1400, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
//#endif
	{ WEAPON_Z4B_FREEDOM, "z4b_freedom",         "自由",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	//{ WEAPON_Z4B_CSG12SS, "z4b_csg12ss",         "CSG-12",           1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_SPRIFLE, "weapon_sprifle",         "狂暴蒸汽",           5500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_INFINITY, "weapon_infinity",    "恒宇双星", 1500, PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
    { WEAPON_INFINITYEX1, "weapon_infinityex1", "星红双子",   1500, PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
    { WEAPON_INFINITYEX2, "weapon_infinityex2", "金红双蝎",     1500, PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
    { WEAPON_INFINITYSS, "weapon_infinityss",  "恒宇银星",       600,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
    { WEAPON_INFINITYSR, "weapon_infinitysr",  "恒宇红星",          600,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
    { WEAPON_INFINITYSB, "weapon_infinitysb",  "恒宇黑星",        600,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
    { WEAPON_ANACONDA, "weapon_anaconda",	 "左轮军魂",			  650,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_M950, "weapon_m950",	 "卡利柯M950",			  1500,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_M950SE, "weapon_m950se",	 "黯夜流光",			  2000,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_SKULL1, "weapon_skull1",	 "噬魂SKULL-1",			  1200,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_SFPISTOL, "weapon_sfpistol",	 "死亡射线",			  1500,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_Y22S2SFPISTOL, "weapon_y22s2sfpistol",	 "死亡射线EX",			  1500,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_MP7A1_CARBINE, "weapon_mp7a1c",      "MP7A1",                 2150, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
    { WEAPON_XM8CARBINE, "weapon_xm8c",        "XM8",                   3250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_SCARLIGHT, "weapon_scarl",       "Scar",                  3250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_M1887, "weapon_m1887",       "退魔圣焰",                 2800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
    { WEAPON_KRISS, "weapon_kriss",       "致命蝎刺",                 1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
    { WEAPON_K1A, "weapon_k1a",         "K1A",                   1850, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
    { WEAPON_THOMPSON, "weapon_thompson",    "汤姆逊",              2000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
    { WEAPON_M14EBR, "weapon_m14ebr",      "咆哮怒焰",               3100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M2, "weapon_m2",      "守护者",               6200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
    { WEAPON_M134, "weapon_m134",      "终结者",               7000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
    { WEAPON_M134EX, "weapon_m134ex",      "终结者EX",               7000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
    { WEAPON_TBARREL, "weapon_tbarrel",         "破碎炙焱",                  2600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
    { WEAPON_M134XMAS, "weapon_m134xmas",         "圣诞终结者",                  7000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
    { WEAPON_MG36, "weapon_mg36",         "开拓者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_CROW7, "weapon_crow7",        "暗鸦CROW-7",                  5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
    { WEAPON_TAR21, "weapon_tar21",       "塔沃尔",                3600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_SKULL5, "weapon_skull5",        "死亡骑士",                  6000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_MG3, "weapon_mg3",         "毁灭者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
    { WEAPON_MG3XMAS, "weapon_mg3xmas",         "圣诞毁灭者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
    { WEAPON_BOW, "weapon_bow",      "鹰眼",               6200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_BALROG7, "weapon_balrog7",      "炎魔",               9000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
    { WEAPON_STARCHASERAR, "weapon_starchaserar",      "灭却星光",               5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_BALROG11, "weapon_balrog11",        "龙炎",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
    { WEAPON_BALROG11B, "weapon_balrog11b",        "凛风",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
    { WEAPON_BALROG11WC, "weapon_balrog11wc",        "黄金龙炎",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
    { WEAPON_SFSMG, "weapon_sfsmg",         "疾风之翼",           1900, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_TMPDRAGON, "weapon_tmpdragon",	 "Tmp金龙",			  1250,  PRIMARY_WEAPON_SLOT,         UNASSIGNED, BUY_SMG },
	{ WEAPON_SFGUN, "weapon_sfgun",         "星际重炮",           3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_ETHEREAL, "weapon_ethereal",         "尘埃之光",           3900, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_RAILGUN, "weapon_railgun",         "爆能磁轨炮",                  7000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_SFSNIPER, "weapon_sfsniper",         "雷神",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M400, "weapon_m400",         "死神M200",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M82, "weapon_m82",         "帕克-黑尔M82",           4700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M24, "weapon_m24",         "狂蟒之吻M24",           4500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_TRG42, "weapon_trg42",         "芬兰之星TRG-42",           4750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_TRG42G, "weapon_trg42g",         "芬兰之星(白金典藏)",           4750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AW50, "weapon_aw50",         "AW50",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
    { WEAPON_PLASMAGUN, "weapon_plasmagun",      "破晓黎明",    0, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ KNIFE_SKULLAXE, "knife_skullaxe",     "旋风",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ WEAPON_M95, "weapon_m95",         "巴雷特",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M95XMAS, "weapon_m95xmas",         "圣诞巴雷特",                  5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_WA2000, "weapon_wa2000",      "狂怒骑士",                4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AS50, "weapon_as50",        "末日骑士",                  5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AS50G, "weapon_as50g",        "末日金骑",                  5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_BENDITA, "weapon_bendita",        "冰封圣骑",                  5500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_BPGM, "weapon_bpgm",        "PGM Hecate Ⅱ战损版",                  4900, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SL8, "weapon_sl8",        "猎魂骑士SL8",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SL8G, "weapon_sl8g",        "猎魂金骑(装弹强化)",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SL8EX, "weapon_sl8ex",        "猎魂骑士EX",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_ZGUN, "weapon_zgun",        "异变之源AWP-Z",                  4800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_STG44, "weapon_stg44",        "咆哮飓风",                  3100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_LIGHTZG, "weapon_lightzg",        "暗影芭比啵啵枪",                  3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_HEAVYZG, "weapon_heavyzg",        "憎恶屠夫噗噗枪",                  3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M249EX, "weapon_m249ep",        "M249丛林之王",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_THANATOS7, "weapon_thanatos7",        "斩魂Thanatos-7",                  9000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_M249EX, "weapon_m249ex",        "碎魂者",                  9000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_SKULL8, "weapon_skull8",        "碎魂利刃SKULL-8",                  6200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_SKULL8, "weapon_skull6",        "碎魂骑士SKULL-6",                  6500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_HK23, "weapon_hk23",        "追击者HK23",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_M60, "weapon_m60",        "掠食者M60E4",                  4700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_MK48, "weapon_mk48",        "劫掠者MK48",                  5500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_K3, "weapon_k3",        "k3",                  4750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_SFMG, "weapon_sfmg",         "赤色彗星",           5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_BISON, "weapon_bison",         "野牛PP-Bison",                  1400, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_M4A1DRAGON, "weapon_m4a1dragon",         "青龙M4A1",                  3100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AK47DRAGON, "weapon_ak47dragon",         "赤龙AK47",                  2500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AK47G, "weapon_ak47g",         "雅金AK",                  2500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SKULL4, "weapon_skull4",         "死亡咆哮Skull-4",                  6150, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ KNIFE_DRAGONSWORD, "knife_dragonsword",     "青龙偃月刀",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_DRAGON, "knife_knifedragon",         "龙吻",                  0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_STRONGKNIFE, "knife_nataknife",      "背刺银刃",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_JKNIFE, "knife_jknife",      "星芒蝶翼",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_COMBAT, "knife_combat",      "灭灵军刺",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_MASTERCOMBAT, "knife_mastercombat",      "灭灵军刺•锯刃",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_HDAGGER, "knife_hdagger",      "兽王铜匕",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_HAMMER, "knife_hammer",      "风暴之锤",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_AXE, "knife_axe",      "摄魂魔镰",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_KATANA, "knife_katana",     "狂花乱舞",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
    { KNIFE_BALROG9, "knife_balrog9",      "爆裂拳套",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
    { KNIFE_JANUS9, "knife_janus9",     "灾厄",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
    { WEAPON_GATLING, "weapon_gatling",      "加特林",               4000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
    { WEAPON_CHAINSAW, "weapon_chainsaw",         "生命收割者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_CHAINSAWM, "weapon_chainsawm",         "死神使者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_CHAINSAWEX, "weapon_chainsawex",         "生命收割者EX",                  4000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
    { WEAPON_CANNON, "weapon_cannon",      "黑龙炮",    3800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	//{ WEAPON_ZOMBIELAW, "weapon_zombielaw",      "test",    100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ GRENADE_HEGRENADE, "weapon_hegrenade",     "高爆手雷",               300, GRENADE_SLOT, UNASSIGNED, BUY_EQUIP },
	{ GRENADE_PUMPKIN, "weapon_pumpkin",     "南瓜手雷",               600, GRENADE_SLOT, UNASSIGNED, BUY_EQUIP },
	//{ WEAPON_CSGO_ZEUS, "csgo_zeus",         "电击枪",                  200, KNIFE_SLOT, UNASSIGNED, BUY_EQUIP },
	//{ GRENADE_HOLYBOMB, "weapon_holybomb",     "圣水手雷",              600, GRENADE_SLOT, UNASSIGNED, BUY_EQUIP },
};

constexpr MoEWeaponBuyInfo_s g_MoEWeaponBuyInfoLocal[] = {
	{ WEAPON_USP, "weapon_usp",      "USP45",    500, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_GLOCK18, "weapon_glock18",      "Glock-18",    400, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_P228, "weapon_p228",      "P228",    600, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_DEAGLE, "weapon_deagle",      "Deagle",    650, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_ELITE, "weapon_elite",      "Elite",    800, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_FIVESEVEN, "weapon_fiveseven",      "FiveSeven",    750, PISTOL_SLOT, UNASSIGNED, BUY_PISTOL },
	{ WEAPON_M3, "weapon_m3",      "M3",    1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_XM1014, "weapon_xm1014",      "XM1014",    3000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_MAC10, "weapon_mac10",      "MAC10",    1400, PRIMARY_WEAPON_SLOT, UNASSIGNED,  BUY_SMG },
	{ WEAPON_TMP, "weapon_tmp",      "TMP",    1250, PRIMARY_WEAPON_SLOT, UNASSIGNED,  BUY_SMG },
	{ WEAPON_MP5N, "weapon_mp5navy",      "MP5",    1500, PRIMARY_WEAPON_SLOT, UNASSIGNED,  BUY_SMG },
	{ WEAPON_UMP45, "weapon_ump45",      "UMP-45",    1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_P90, "weapon_p90",      "P90",    2350, PRIMARY_WEAPON_SLOT, UNASSIGNED,  BUY_SMG },
	{ WEAPON_GALIL, "weapon_galil",      "Galil",    2000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_FAMAS, "weapon_famas",      "Famas",    2250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AK47, "weapon_ak47",      "CV-47",    2500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SCOUT, "weapon_scout",      "Scout",    2750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M4A1, "weapon_m4a1",      "M4A1",    3100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AUG, "weapon_aug",      "AUG",    3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SG552, "weapon_sg552",      "SG552",    3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SG550, "weapon_sg550",      "SG550",    4200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AWP, "weapon_awp",      "AWP",    4750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_G3SG1, "weapon_g3sg1",      "G3SG1",    5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M249, "weapon_m249",      "M249",    5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },

	{ WEAPON_KNIFE, "weapon_knife", "海豹短刀",            0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ WEAPON_SPRIFLE, "weapon_sprifle",         "狂暴蒸汽",           5500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_INFINITY, "weapon_infinity",    "恒宇双星", 1500, PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_INFINITYEX1, "weapon_infinityex1", "星红双子",   1500, PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_INFINITYEX2, "weapon_infinityex2", "金红双蝎",     1500, PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_INFINITYSS, "weapon_infinityss",  "恒宇银星",       600,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_INFINITYSR, "weapon_infinitysr",  "恒宇红星",          600,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_INFINITYSB, "weapon_infinitysb",  "恒宇黑星",        600,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_ANACONDA, "weapon_anaconda",	 "左轮军魂",			  650,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_M950, "weapon_m950",	 "卡利柯M950",			  1500,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_M950SE, "weapon_m950se",	 "黯夜流光",			  2000,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_SKULL1, "weapon_skull1",	 "噬魂SKULL-1",			  1200,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_SFPISTOL, "weapon_sfpistol",	 "死亡射线",			  1500,  PISTOL_SLOT,         UNASSIGNED, BUY_PISTOL },
	{ WEAPON_MP7A1_CARBINE, "weapon_mp7a1c",      "MP7A1",                 2150, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_XM8CARBINE, "weapon_xm8c",        "XM8",                   3250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SCARLIGHT, "weapon_scarl",       "Scar",                  3250, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M1887, "weapon_m1887",       "退魔圣焰",                 2800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_KRISS, "weapon_kriss",       "致命蝎刺",                 1700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_K1A, "weapon_k1a",         "K1A",                   1850, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_THOMPSON, "weapon_thompson",    "汤姆逊",              2000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_M14EBR, "weapon_m14ebr",      "咆哮怒焰",               3100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M2, "weapon_m2",      "守护者",               6200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_M134, "weapon_m134",      "终结者",               7000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_M134EX, "weapon_m134ex",      "终结者EX",               7000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_TBARREL, "weapon_tbarrel",         "破碎炙焱",                  2600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_M134XMAS, "weapon_m134xmas",         "圣诞终结者",                  7000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_MG36, "weapon_mg36",         "开拓者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_TAR21, "weapon_tar21",       "塔沃尔",                3600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SKULL5, "weapon_skull5",        "死亡骑士",                  6000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_MG3, "weapon_mg3",         "毁灭者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_MG3XMAS, "weapon_mg3xmas",         "圣诞毁灭者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_BOW, "weapon_bow",      "鹰眼",               6200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_BALROG7, "weapon_balrog7",      "炎魔",               9000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_STARCHASERAR, "weapon_starchaserar",      "灭却星光",               5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_BALROG11, "weapon_balrog11",        "龙炎",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_BALROG11B, "weapon_balrog11b",        "凛风",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_BALROG11WC, "weapon_balrog11wc",        "黄金龙炎",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_SFSMG, "weapon_sfsmg",         "疾风之翼",           1900, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_TMPDRAGON, "weapon_tmpdragon",	 "Tmp金龙",			  1250,  PRIMARY_WEAPON_SLOT,         UNASSIGNED, BUY_SMG },
	{ WEAPON_SFGUN, "weapon_sfgun",         "星际重炮",           3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SFSNIPER, "weapon_sfsniper",         "雷神",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M400, "weapon_m400",         "死神M200",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M82, "weapon_m82",         "帕克-黑尔M82",           4700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M24, "weapon_m24",         "狂蟒之吻M24",           4500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_TRG42, "weapon_trg42",         "芬兰之星TRG-42",           4750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_TRG42G, "weapon_trg42g",         "芬兰之星(白金典藏)",           4750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AW50, "weapon_aw50",         "AW50",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_PLASMAGUN, "weapon_plasmagun",      "破晓黎明",    0, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ KNIFE_SKULLAXE, "knife_skullaxe",     "旋风",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ WEAPON_M95, "weapon_m95",         "巴雷特",           5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M95XMAS, "weapon_m95xmas",         "圣诞巴雷特",                  5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_WA2000, "weapon_wa2000",      "狂怒骑士",                4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AS50, "weapon_as50",        "末日骑士",                  5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AS50G, "weapon_as50g",        "末日金骑",                  5000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_BENDITA, "weapon_bendita",        "冰封圣骑",                  5500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_BPGM, "weapon_bpgm",        "PGM Hecate Ⅱ战损版",                  4900, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SL8, "weapon_sl8",        "猎魂骑士SL8",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SL8G, "weapon_sl8g",        "猎魂金骑(装弹强化)",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SL8EX, "weapon_sl8ex",        "猎魂骑士EX",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_ZGUN, "weapon_zgun",        "异变之源AWP-Z",                  4800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_STG44, "weapon_stg44",        "咆哮飓风",                  3100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_LIGHTZG, "weapon_lightzg",        "暗影芭比啵啵枪",                  3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_HEAVYZG, "weapon_heavyzg",        "憎恶屠夫噗噗枪",                  3500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_M249EX, "weapon_m249ep",        "M249丛林之王",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_M249EX, "weapon_m249ex",        "碎魂者",                  9000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_SKULL8, "weapon_skull8",        "碎魂利刃SKULL-8",                  6200, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_SKULL8, "weapon_skull6",        "碎魂骑士SKULL-6",                  6500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_HK23, "weapon_hk23",        "追击者HK23",                  4600, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_M60, "weapon_m60",        "掠食者M60E4",                  4700, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_MK48, "weapon_mk48",        "劫掠者MK48",                  5500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_K3, "weapon_k3",        "k3",                  4750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_SFMG, "weapon_sfmg",         "赤色彗星",           5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_MG },
	{ WEAPON_BISON, "weapon_bison",         "野牛PP-Bison",                  1400, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SMG },
	{ WEAPON_M4A1DRAGON, "weapon_m4a1dragon",         "青龙M4A1",                  3100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AK47DRAGON, "weapon_ak47dragon",         "赤龙AK47",                  2500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_AK47G, "weapon_ak47g",         "雅金AK",                  2500, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ WEAPON_SKULL4, "weapon_skull4",         "死亡咆哮Skull-4",                  6150, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_RIFLE },
	{ KNIFE_DRAGONSWORD, "knife_dragonsword",     "青龙偃月刀",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_DRAGON, "knife_knifedragon",         "龙吻",                  0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_STRONGKNIFE, "knife_nataknife",      "背刺银刃",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_JKNIFE, "knife_jknife",      "星芒蝶翼",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_COMBAT, "knife_combat",      "灭灵军刺",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_MASTERCOMBAT, "knife_mastercombat",      "灭灵军刺•锯刃",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_HDAGGER, "knife_hdagger",      "兽王铜匕",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_HAMMER, "knife_hammer",      "风暴之锤",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_AXE, "knife_axe",      "摄魂魔镰",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_KATANA, "knife_katana",     "狂花乱舞",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ KNIFE_BALROG9, "knife_balrog9",      "爆裂拳套",    0, KNIFE_SLOT, UNASSIGNED, BUY_KNIFE },
	{ KNIFE_JANUS9, "knife_janus9",     "灾厄",               0,    KNIFE_SLOT,          UNASSIGNED, BUY_KNIFE },
	{ WEAPON_GATLING, "weapon_gatling",      "加特林",               4000, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_SHOTGUN },
	{ WEAPON_CHAINSAW, "weapon_chainsaw",         "生命收割者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_CHAINSAWM, "weapon_chainsawm",         "死神使者",                  5750, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ WEAPON_CANNON, "weapon_cannon",      "黑龙炮",    3800, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	//{ WEAPON_ZOMBIELAW, "weapon_zombielaw",      "test",    100, PRIMARY_WEAPON_SLOT, UNASSIGNED, BUY_EQUIP },
	{ GRENADE_HEGRENADE, "weapon_hegrenade",     "高爆手雷",               300, GRENADE_SLOT, UNASSIGNED, BUY_EQUIP },
	{ GRENADE_PUMPKIN, "weapon_pumpkin",     "南瓜手雷",               600, GRENADE_SLOT, UNASSIGNED, BUY_EQUIP },
	//{ WEAPON_CSGO_ZEUS, "csgo_zeus",         "电击枪",                  200, KNIFE_SLOT, UNASSIGNED, BUY_EQUIP },
	//{ GRENADE_HOLYBOMB, "weapon_holybomb",     "圣水手雷",              600, GRENADE_SLOT, UNASSIGNED, BUY_EQUIP },
};

}

#endif
